from pathlib import Path
import matplotlib.pyplot as plt
ROOT=Path(__file__).parent
INFO={
71:("Project 071 - Medical Diagnosis Support Tool",[1,4,0],["Top match","Patterns","Red flags"],"The intake example matched all four influenza-like terms and triggered no emergency red flag. The response is framed as pattern support and routes the user to clinical review rather than presenting a definitive diagnosis.","Exact symptom overlap makes this workflow auditable. The safety value is the independent red-flag route: chest pain or shortness of breath overrides ordinary similarity and recommends emergency evaluation.","The knowledge base is deliberately narrow. Clinical deployment requires validated terminology, prevalence-aware differentials, age and medication context, and governance by licensed professionals."),
72:("Project 072 - Insurance Claim Classifier",[.784,.5846,.247],["Accuracy","Fraud F1","Fraud rate"],"On 1,000 Kaggle auto claims, the model reached 78.4% accuracy and 0.5846 fraud F1 against a 24.7% fraud rate.","Accuracy alone would flatter a majority-class model. The fraud recall of 61.29% and precision of 55.88% show a useful screening signal, but also a material review burden and missed-case risk.","This should prioritize investigations, not deny claims. Thresholds need cost-based calibration, drift monitoring, and fairness testing across protected groups."),
73:("Project 073 - Drug Similarity Finder",[1,.2222,8],["Exact match","Next match","Compounds"],"The PubChem-backed search ranked acetaminophen itself at 1.000 and aspirin second at 0.2222 across eight common medicines.","The low second-place score is informative: these medicines may share analgesic use without close Morgan-fingerprint structure. Structural and therapeutic similarity are different questions and should not be conflated.","A useful discovery system needs a larger ChEMBL or PubChem library, stereochemistry controls, activity targets, and expert interpretation; similarity is not evidence of equivalent safety or efficacy."),
74:("Project 074 - Financial Forecasting Agent",[333.69,334.04,7.463],["Last close","30-day forecast","Holdout MAE"],"The ARIMA model used 1,255 AAPL observations. Its 30-session point forecast was $334.04 versus a latest close of $333.69, with a wide $296.69–$371.39 interval.","The near-flat point estimate is less important than the interval. A $74.70 span signals substantial uncertainty, while the 20-day holdout MAE of $7.46 provides an empirical scale for typical forecast error.","This is trend analysis, not investment advice. Exogenous events, splits, regime changes, and transaction costs are outside the univariate model."),
75:("Project 075 - AI Loan Eligibility Checker",[.7792,.7911,.6873],["Accuracy","ROC AUC","Approval rate"],"The Kaggle loan model evaluated 614 applications, reaching 77.92% accuracy and 0.7911 ROC AUC; 68.73% of the records were approved.","ROC AUC shows useful ranking power beyond the majority approval rate. Because lending errors have unequal consequences, the classification threshold should be chosen from a documented approval and loss policy rather than fixed at 0.5.","This is a pre-screening demonstration. Protected attributes, disparate impact, adverse-action reasons, calibration, and regulatory review are mandatory before real lending use."),
76:("Project 076 - Retail Sales Predictor",[104.25,87.02,2610.5],["Holdout MAE","Daily forecast","30-day units"],"Using 374 days from UCI Online Retail, the seasonal forecast projects 2,610.5 units over 30 days, or 87.02 per day. Holdout MAE was 104.25 units.","The error exceeds the projected daily mean, so the point forecast is not precise enough for tight replenishment. It is better suited to a broad capacity range while promotions, stockouts, and outlier orders are modeled explicitly.","The series covers one high-activity product and zeros on non-selling days. Hierarchical store/product modeling and prediction intervals are the next steps."),
77:("Project 077 - Customer Churn Predictor",[.7399,.8389,.2654],["Accuracy","ROC AUC","Churn rate"],"The IBM Telco model trained on 7,043 customers and produced 73.99% accuracy with 0.8389 ROC AUC against a 26.54% churn rate.","The gap between accuracy and ROC AUC indicates that ranking is stronger than the default thresholded decision. Retention teams should select a cutoff from intervention capacity and expected value, then evaluate lift in the contacted deciles.","This is observational churn data. Model scores do not prove that a retention offer will change behavior; an experiment is needed to estimate incremental impact."),
78:("Project 078 - Visual Price Tag Detection for Retail",[2,.673,1],["Prices found","Mean confidence","Exact count"],"EasyOCR located both prices in the retail fixture: $3.49 and 7.99. Mean OCR confidence was 0.673, with the second price at 0.950 and the first at 0.397.","The count is correct, but confidence exposes an operational difference hidden by exact detection: the currency symbol and typography depressed the first tag. Low-confidence reads should be queued for review rather than silently accepted.","The fixture is controlled. Store glare, angled shelves, small tags, crossed-out prices, and multiple currencies require a photographed benchmark and detector-plus-OCR evaluation."),
79:("Project 079 - Product Review Analyzer",[.804,.4436,4],["Test accuracy","Positive probability","Aspects"],"The sentiment model achieved 80.4% accuracy on 1,000 UCI Amazon reviews. The mixed laptop review scored 44.36% positive while exposing four aspects: battery, display, performance, and support.","A single overall label misses the commercial signal. Battery is negative while display, performance, and support are positive; the aspect list preserves where product and service teams should act.","The training labels are sentence-level and binary. Aspect-specific polarity, neutral sentiment, sarcasm, and category drift need additional annotation."),
80:("Project 080 - Doctor-Patient Conversational AI",[2,3,0],["Patient turns","Symptoms","Red flags"],"The intake dialogue retained two patient turns, extracted fever, sore throat, and cough, and produced a concise hand-off with no emergency flag.","The assistant asks for duration before expanding the assessment, which makes the exchange purposeful rather than conversational filler. Red flags are checked at every turn and override the ordinary follow-up path.","The dialogue engine is an intake aid only. Identity, consent, privacy controls, medication history, clinician review, and validated escalation protocols are required for healthcare use."),
}
PIPE={71:["Parse symptoms","Match patterns","Check red flags","Route"],72:["Load claims","Encode fields","Train forest","Review fraud"],73:["Read SMILES","Fingerprint","Tanimoto score","Rank"],74:["Load prices","Fit ARIMA","Backtest","Forecast"],75:["Clean applications","Encode","Fit logistic","Score"],76:["Aggregate sales","Fit seasonality","Backtest","Forecast"],77:["Prepare customers","Encode","Fit logistic","Rank risk"],78:["Read image","OCR regions","Filter prices","Return boxes"],79:["Vectorize reviews","Classify","Extract aspects","Summarize"],80:["Store turn","Extract symptoms","Check red flags","Handoff"]}
REQ={71:"",72:"pandas\nscikit-learn\nkagglehub",73:"rdkit\nrequests",74:"pandas\nstatsmodels",75:"pandas\nscikit-learn\nkagglehub",76:"pandas\nstatsmodels\nopenpyxl\nrequests",77:"pandas\nscikit-learn\nkagglehub",78:"easyocr\nopencv-python-headless\ntorch\nPillow",79:"scikit-learn\nrequests",80:""}
SOURCES={71:"The project uses the symptom-pattern knowledge base specified in the course PDF; it is not a patient dataset.",72:"Kaggle Auto Insurance Claims Data (`buntyshah/auto-insurance-claims-data`), 1,000 records.",73:"Canonical structures retrieved from the NIH PubChem PUG REST API by `download_data.py`.",74:"AAPL daily reference data from Plotly's public finance dataset, shared with Project 11.",75:"Kaggle Loan Prediction Problem Dataset (`altruistdelhite04/loan-prediction-problem-dataset`), 614 labeled training applications.",76:"UCI Machine Learning Repository Online Retail dataset (dataset 352); daily units are aggregated for the product sold on the most distinct days.",77:"IBM Telco Customer Churn dataset distributed through Kaggle (`blastchar/telco-customer-churn`), 7,043 customers.",78:"A deterministic two-product retail fixture generated by `make_fixture.py`; no private store imagery is used.",79:"UCI Sentiment Labelled Sentences dataset (dataset 331), Amazon cell reviews subset, 1,000 labeled sentences.",80:"The demonstration uses a scripted, fictional intake dialogue and stores no patient data."}
for n,(folder_name,vals,labs,opening,finding,limit) in INFO.items():
 f=ROOT/folder_name;a=f/'analysis_assets';a.mkdir(exist_ok=True);fig,ax=plt.subplots(figsize=(9,4.8));bars=ax.bar(labs,vals,color=['#2563eb','#0f766e','#d97706']);ax.bar_label(bars,fmt='%.4g',padding=3);ax.set_title('Observed validation results',loc='left',fontsize=13,fontweight='bold',color='#172554');ax.grid(axis='y',alpha=.22);ax.spines[['top','right']].set_visible(False);fig.tight_layout();fig.savefig(a/'validation_results.png',dpi=150);plt.close(fig)
 fig,ax=plt.subplots(figsize=(9,3.5));ax.axis('off')
 for i,item in enumerate(PIPE[n]):
  x=.12+i*.25;ax.text(x,.52,item,ha='center',va='center',fontsize=10.5,color='white',bbox=dict(boxstyle='round,pad=.65',fc='#172554',ec='none'))
  if i<3:ax.annotate('',xy=(x+.18,.52),xytext=(x+.08,.52),arrowprops=dict(arrowstyle='->',lw=2,color='#64748b'))
 ax.set_title('Execution path',loc='left',fontsize=13,fontweight='bold',color='#172554');fig.tight_layout();fig.savefig(a/'execution_path.png',dpi=150);plt.close(fig)
 title=folder_name.split(' - ',1)[1];(f/'ANALYSIS_REPORT.md').write_text(f'''# Analysis Report: {title}\n\n**Author:** Edward Ocran\n\n## Executive finding\n\n{opening}\n\n![Observed validation results](analysis_assets/validation_results.png)\n\n## Evidence and interpretation\n\n{finding}\n\n![Execution path](analysis_assets/execution_path.png)\n\n## Method\n\nThe implementation follows the supplied PDF workflow and reports the held-out or end-to-end validation result. Dataset retrieval and provenance are separated from modeling so the experiment can be repeated without committing third-party data.\n\n## Limitations and next step\n\n{limit}\n\n## Reproduce\n\n```powershell\npip install -r requirements.txt\npython download_data.py  # where included\npython main.py --help\npython -m unittest -v test_project.py\n```\n''',encoding='utf-8')
 (f/'DATASET.md').write_text(f'# Data provenance\n\n**Author:** Edward Ocran\n\n{SOURCES[n]}\n\nDownloaded source files are excluded from Git and recreated with the included retrieval scripts where applicable.\n',encoding='utf-8');(f/'requirements.txt').write_text(REQ[n]+'\n',encoding='utf-8')
 dl='- `download_data.py` — source retrieval and preparation.\n' if (f/'download_data.py').exists() else '';(f/'README.md').write_text(f'''# Project {n}: {title}\n\n**Author:** Edward Ocran\n\n## Objective\n\nImplement the course workflow for {title.lower()} with inspectable inputs, outputs, and validation.\n\n## Included\n\n- `main.py` — runnable implementation.\n- `test_project.py` — behavior test.\n- `ANALYSIS_REPORT.md` — detailed findings and charts.\n- `DATASET.md` — provenance and handling.\n{dl}- `analysis_assets/` — rendered report figures.\n\n## Run\n\n```powershell\npip install -r requirements.txt\npython main.py --help\npython -m unittest -v test_project.py\n```\n\nThe course PDF is not redistributed.\n''',encoding='utf-8')
print('generated 71-80 reports')
